### PR TITLE
Update service for production

### LINKED ISSUE #7: Update service for production

### PR DESCRIPTION
**Pull request by rmarquis**

### CODE REVIEW

**Comment by rmarquis** [comment]
Note: The test passes locally, but fails in the pipeeline. Investigate.

**Review by andrptrc — COMMENTED** [review]
We need to understand why we need to comment the test in the service before merging the update

**Comment by rmarquis** [comment]
We shouldn't comment the test, we need to find out why the issue happens and fix it.
From the actions log:

```
ERROR:    [2024-03-28 13:13:24,965]  [common_code.service.service]: 	Error updating service in the engine: No handler found for request <Request 'http://localhost:35433/services/None' [PATCH]> with data b'{"status": "disabled"}'.Ordered matchers:
    none
```
Something goes wrong in the pipeline, but I am unable to reproduce the issue locally. @andrptrc Any idea here?

**Review by andrptrc — APPROVED** [review]

**Comment by andrptrc** [comment]
The test checking for WARNING logs was causing issue because loading the model creates a Warning message. Changed test to check only for the desired Warning message. Need to change this in every service to prevent other problems in the future

**Pull request merged**
